apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serverPod
  template:
    metadata:
      labels:
        app: serverPod
    spec:
      containers:
      - name: server
        image: chat-backend-backend:v1.0
        ports:
          - containerPort: 5121
