apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientPod
  template:
    metadata:
      labels:
        app: clientPod
    spec:
      containers:
      - name: client
        image: chat-backend-client:v1.0
        ports:
          - containerPort: 3000
